/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen2p2_junniorsauceda;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author Junnior Sauceda
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        rellenarArtistas();
        rellenarClientes();
        rellenarListas();
        Nodo = (DefaultMutableTreeNode) jtr_treElim.getModel().getRoot();
        Users.addAll(Clients);
        Users.addAll(Artists);
        jlb_artista.setVisible(false);
        jtf_NombreArtist.setVisible(false);
        jlb_artista.setEnabled(false);
        jtf_NombreArtist.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JD_CrearAcount = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtf_Contra = new javax.swing.JTextField();
        jtf_Nombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jsp_Edad = new javax.swing.JSpinner();
        jbt_CrearCuenta = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jcb_TipUs = new javax.swing.JComboBox<>();
        jlb_artista = new javax.swing.JLabel();
        jtf_NombreArtist = new javax.swing.JTextField();
        JD_Cliente = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Jlst_canciones = new javax.swing.JList<>();
        jProgressBar1 = new javax.swing.JProgressBar();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        JD_Artista = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtf_TituloPubli = new javax.swing.JTextField();
        jtf_FechaPubli = new javax.swing.JTextField();
        jsp_cantSongs = new javax.swing.JSpinner();
        jbt_CrearAlbum = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jtf_TituloSingle = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jtf_FechaSingle = new javax.swing.JTextField();
        Bt_AddSingle = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jtf_TituloCancion = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jsp_DuraCancion = new javax.swing.JSpinner();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtr_treElim = new javax.swing.JTree();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtree_Listar = new javax.swing.JTree();
        JD_CrearCanciones = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jtf_TituloSong = new javax.swing.JTextField();
        jsp_DuraSong = new javax.swing.JSpinner();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Jtf_Contraseña = new javax.swing.JTextField();
        Jtf_Usuario = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(0, 102, 0));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Crear Cuenta");

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel5.setText("Contraseña:");

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel6.setText("Nombre:");

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel7.setText("Edad:");

        jsp_Edad.setModel(new javax.swing.SpinnerNumberModel(12, 12, null, 1));

        jbt_CrearCuenta.setText("Crear Cuenta");
        jbt_CrearCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbt_CrearCuentaMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel8.setText("Tipo De Usuario:");

        jcb_TipUs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Artista" }));
        jcb_TipUs.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcb_TipUsItemStateChanged(evt);
            }
        });

        jlb_artista.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jlb_artista.setText("Nombre Artistico:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtf_Contra, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jtf_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(188, 188, 188))
                    .addComponent(jsp_Edad)
                    .addComponent(jLabel8)
                    .addComponent(jcb_TipUs, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(120, 120, 120))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(303, 303, 303))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(jlb_artista))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jtf_NombreArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(jbt_CrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtf_Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jcb_TipUs))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtf_Contra, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jsp_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jlb_artista, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_NombreArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jbt_CrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JD_CrearAcountLayout = new javax.swing.GroupLayout(JD_CrearAcount.getContentPane());
        JD_CrearAcount.getContentPane().setLayout(JD_CrearAcountLayout);
        JD_CrearAcountLayout.setHorizontalGroup(
            JD_CrearAcountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JD_CrearAcountLayout.setVerticalGroup(
            JD_CrearAcountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(0, 51, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(Jlst_canciones);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 280, 450));

        jProgressBar1.setMaximum(60);
        jPanel3.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 520, 20));

        jButton5.setText("Reproducir");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 90, 40));

        jButton6.setText("Pausar/Reanudar");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 120, 40));

        javax.swing.GroupLayout JD_ClienteLayout = new javax.swing.GroupLayout(JD_Cliente.getContentPane());
        JD_Cliente.getContentPane().setLayout(JD_ClienteLayout);
        JD_ClienteLayout.setHorizontalGroup(
            JD_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 849, Short.MAX_VALUE)
        );
        JD_ClienteLayout.setVerticalGroup(
            JD_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(102, 153, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel9.setText("Spofiry");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 90, 40));

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel10.setText("Bienvenido Artista!");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel11.setText("Titulo:");

        jLabel12.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel12.setText("Fecha de Lanzamiento:");

        jLabel13.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel13.setText("Cantidad de Canciones:");

        jtf_TituloPubli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_TituloPubliActionPerformed(evt);
            }
        });

        jtf_FechaPubli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_FechaPubliActionPerformed(evt);
            }
        });

        jsp_cantSongs.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jbt_CrearAlbum.setText("Crear Album");
        jbt_CrearAlbum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbt_CrearAlbumMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jtf_TituloPubli, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtf_FechaPubli, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jsp_cantSongs, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(139, 139, 139))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(jbt_CrearAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jsp_cantSongs, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_TituloPubli, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtf_FechaPubli, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jbt_CrearAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        jTabbedPane1.addTab("Crear Album", jPanel5);

        jPanel6.setBackground(new java.awt.Color(0, 102, 153));

        jLabel17.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel17.setText("Titulo:");

        jtf_TituloSingle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_TituloSingleActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel18.setText("Fecha de Lanzamiento:");

        jtf_FechaSingle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_FechaSingleActionPerformed(evt);
            }
        });

        Bt_AddSingle.setText("Crear Single");
        Bt_AddSingle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Bt_AddSingleMouseClicked(evt);
            }
        });
        Bt_AddSingle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_AddSingleActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel19.setText("Cancion:");

        jLabel20.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel20.setText("Duracion(Segundos):");

        jsp_DuraCancion.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jtf_TituloSingle, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtf_FechaSingle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 251, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19)
                    .addComponent(jtf_TituloCancion)
                    .addComponent(jsp_DuraCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(Bt_AddSingle, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_TituloSingle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(jtf_TituloCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtf_FechaSingle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(jsp_DuraCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addComponent(Bt_AddSingle, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crear Single", jPanel6);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 409, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Editar Album", jPanel9);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 409, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Editar Single", jPanel10);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Musica");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Albumes");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Singles");
        treeNode1.add(treeNode2);
        jtr_treElim.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane2.setViewportView(jtr_treElim);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(584, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Eliminar Lanzamiento", jPanel11);

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Artista");
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Albumes");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Single");
        treeNode1.add(treeNode2);
        jtree_Listar.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane3.setViewportView(jtree_Listar);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(582, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listar(Este si funciona)", jPanel8);

        jPanel4.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 840, 440));

        javax.swing.GroupLayout JD_ArtistaLayout = new javax.swing.GroupLayout(JD_Artista.getContentPane());
        JD_Artista.getContentPane().setLayout(JD_ArtistaLayout);
        JD_ArtistaLayout.setHorizontalGroup(
            JD_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
        );
        JD_ArtistaLayout.setVerticalGroup(
            JD_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(0, 102, 0));

        jLabel14.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel14.setText("Crear Cancion");

        jLabel15.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel15.setText("Titulo:");

        jLabel16.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel16.setText("Duracion(Segundos):");

        jsp_DuraSong.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jButton3.setText("Agregar Cancion");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jLabel14))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)
                            .addComponent(jtf_TituloSong, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(jsp_DuraSong)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jtf_TituloSong, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jsp_DuraSong, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JD_CrearCancionesLayout = new javax.swing.GroupLayout(JD_CrearCanciones.getContentPane());
        JD_CrearCanciones.getContentPane().setLayout(JD_CrearCancionesLayout);
        JD_CrearCancionesLayout.setHorizontalGroup(
            JD_CrearCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JD_CrearCancionesLayout.setVerticalGroup(
            JD_CrearCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Spofiry");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 120, 50));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Contraseña:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 140, 30));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Usuario:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 100, 30));
        jPanel1.add(Jtf_Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 350, 50));
        jPanel1.add(Jtf_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 350, 50));

        jButton1.setText("Iniciar Sesion");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 180, 80));

        jButton2.setText("Crear Cuenta");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 170, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcb_TipUsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcb_TipUsItemStateChanged
        // TODO add your handling code here:
        if (jcb_TipUs.getSelectedIndex() == 1) {

            jlb_artista.setEnabled(true);
            jtf_NombreArtist.setEnabled(true);
            jlb_artista.setVisible(true);
            jtf_NombreArtist.setVisible(true);
        } else {
            jlb_artista.setVisible(false);
            jtf_NombreArtist.setVisible(false);
            jlb_artista.setEnabled(false);
            jtf_NombreArtist.setEnabled(false);

        }
    }//GEN-LAST:event_jcb_TipUsItemStateChanged

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        JD_CrearAcount.pack();
        JD_CrearAcount.setModal(true);
        JD_CrearAcount.setLocationRelativeTo(this);
        JD_CrearAcount.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jbt_CrearCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbt_CrearCuentaMouseClicked
        // TODO add your handling code here:
        try {
            boolean existe = false;
            String Nombre = jtf_Nombre.getText();
            for (Usuario User : Users) {
                if (User.getUserName().equals(Nombre)) {
                    existe = true;
                }
            }
            if (existe) {
                JOptionPane.showMessageDialog(JD_CrearAcount, "El nombre se Usuario ya esta en uso");
            } else {
                if (jcb_TipUs.getSelectedIndex() == 0) {
                    if ((Integer.parseInt(jsp_Edad.getValue().toString())) < 12) {
                        JOptionPane.showMessageDialog(JD_CrearAcount, "El Usuario debe tener ser mayor de 12 años");
                    } else {

                        String Contraseña = jtf_Contra.getText();
                        int edad = Integer.parseInt(jsp_Edad.getValue().toString());

                        Cliente c = new Cliente(Nombre, Contraseña, edad);
                        Users.add(c);
                        Clients.add(c);

                        AdminClientes Admin = new AdminClientes("./Clientes.secs");
                        Admin.cargarArchivo();
                        Admin.setCliente(c);
                        Admin.escribirArchivo();
                        JOptionPane.showMessageDialog(JD_CrearAcount, "Se ha creado el cliente");
                    }
                } else {
                    if ((Integer.parseInt(jsp_Edad.getValue().toString())) < 18) {
                        JOptionPane.showMessageDialog(JD_CrearAcount, "El artista debe ser mayor de 18 años");
                    } else {

                        String Contraseña = jtf_Contra.getText();
                        String autism = jtf_NombreArtist.getText();
                        int edad = Integer.parseInt(jsp_Edad.getValue().toString());

                        Artista c = new Artista(autism, Nombre, Contraseña, edad);
                        Artists.add(c);
                        Users.add(c);
                        AdminListaArtist Admin = new AdminListaArtist("./Artistas.secs");
                        Admin.cargarArchivo();
                        Admin.setArtista(c);
                        Admin.escribirArchivo();
                        JOptionPane.showMessageDialog(JD_CrearAcount, "Se ha creado el artista");
                    }

                }
                JD_CrearAcount.setVisible(false);
                jtf_Nombre.setText("");
                jtf_Contra.setText("");
                jtf_NombreArtist.setText("");
                jsp_Edad.setValue(12);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(JD_CrearAcount, "Error");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jbt_CrearCuentaMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        try {
            String nom = Jtf_Usuario.getText();
            String Contra = Jtf_Contraseña.getText();
            boolean existe = false;
            boolean artista = false;
            for (Usuario User : Users) {
                if (User instanceof Artista) {
                    if ((((Artista) User).getUserName().equals(nom)) && ((((Artista) User).getPassword()).equals(Contra))) {
                        Autista = ((Artista) User);
                        artista = true;
                        existe = true;
                    }
                } else {
                    if ((((Cliente) User).getUserName().equals(nom)) && ((((Cliente) User).getPassword()).equals(Contra))) {
                        Usu = ((Cliente) User);
                        artista = false;
                        existe = true;
                    }
                }
            }
            if (existe) {
                Jtf_Usuario.setText("");
                Jtf_Contraseña.setText("");
                if (artista) {
                    Artista = nom;
                    JD_Artista.pack();
                    JD_Artista.setModal(true);
                    JD_Artista.setLocationRelativeTo(this);
                    JD_Artista.setVisible(true);
                } else {
                    rellenarCanciones();
                    DefaultListModel D = new DefaultListModel();
                    D.addAll(Canciones);
                    Jlst_canciones.setModel(D);
                    JD_Cliente.pack();
                    JD_Cliente.setModal(true);
                    JD_Cliente.setLocationRelativeTo(this);
                    JD_Cliente.setVisible(true);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Usuario o contraseña invalidos");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error");
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jtf_TituloPubliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_TituloPubliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_TituloPubliActionPerformed

    private void jtf_FechaPubliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_FechaPubliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_FechaPubliActionPerformed

    private void jbt_CrearAlbumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbt_CrearAlbumMouseClicked
        // TODO add your handling code here:
        String title = jtf_TituloPubli.getText();
        String publi = jtf_FechaPubli.getText();

        al = new Album(Integer.parseInt(jsp_cantSongs.getValue().toString()), title, publi, 0);
        Autista.getAlbumes().add(al);
        BufferedWriter bw = null;
        FileWriter fw = null;
        try {

            File fichero = null;

            fichero = new File("./Lanzamientos.txt");
            String Lanza = "Album" + ";" + al.getTituloPubli() + ";" + al.getLanzaamiento() + ";" + al.getLikes() + ";" + Artista + "\n";

            fw = new FileWriter(fichero, true);
            bw = new BufferedWriter(fw);
            bw.write(Lanza);
            bw.flush();
            JOptionPane.showMessageDialog(JD_Artista,
                    "Album Creado");

        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            bw.close();
            fw.close();
        } catch (IOException ex) {
        }
        //fin IF
        jtf_TituloPubli.setText("");
        jtf_FechaPubli.setText("");
        jsp_cantSongs.setValue(1);
        JD_CrearCanciones.pack();
        JD_CrearCanciones.setModal(true);
        JD_CrearCanciones.setLocationRelativeTo(this);
        JD_CrearCanciones.setVisible(true);

    }//GEN-LAST:event_jbt_CrearAlbumMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:

        String title = jtf_TituloSong.getText();
        double temp = (Integer.parseInt(jsp_DuraSong.getValue().toString()) / 60);
        Cancion c = new Cancion(title, al.getTituloPubli(), temp);
        al.setCancion(c);
        Autista.getCanciones().add(c);
        cont++;
        BufferedWriter bw = null;
        FileWriter fw = null;
        try {

            File fichero = null;

            fichero = new File("./Canciones.txt");
            String Lanza = c.getPapa() + ";" + c.getTitulo() + ";" + c.getDuracion() + "\n";

            fw = new FileWriter(fichero, true);
            bw = new BufferedWriter(fw);
            bw.write(Lanza);
            bw.flush();
            JOptionPane.showMessageDialog(JD_CrearCanciones,
                    "Cancion Agregada");

        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            bw.close();
            fw.close();
        } catch (IOException ex) {
        }
        if (cont == al.getCant()) {
            JD_CrearCanciones.setVisible(false);
            cont = 0;
        }
        jtf_TituloSong.setText("");
        jsp_DuraSong.setValue(1);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jtf_TituloSingleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_TituloSingleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_TituloSingleActionPerformed

    private void jtf_FechaSingleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_FechaSingleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_FechaSingleActionPerformed

    private void Bt_AddSingleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_AddSingleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bt_AddSingleActionPerformed

    private void Bt_AddSingleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt_AddSingleMouseClicked
        // TODO add your handling code here:
        Cancion C = new Cancion(jtf_TituloCancion.getText(), jtf_TituloSingle.getText(), Integer.parseInt(jsp_DuraCancion.getValue().toString()));
        Single s = new Single(C, jtf_TituloCancion.getText(), jtf_FechaSingle.getText(), 0);
        Autista.getCanciones().add(C);
        BufferedWriter bw = null;
        FileWriter fw = null;
        try {

            File fichero = null;

            fichero = new File("./Lanzamientos.txt");
            String Lanza = "Single" + ";" + s.getTituloPubli() + ";" + s.getLanzaamiento() + ";" + s.getLikes() + ";" + Artista + "\n";

            fw = new FileWriter(fichero, true);
            bw = new BufferedWriter(fw);
            bw.write(Lanza);
            bw.flush();

        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            bw.close();
            fw.close();
        } catch (IOException ex) {
        }

        fw = null;
        bw = null;
        try {

            File fichero = null;

            fichero = new File("./Canciones.txt");
            String Lanza = C.getPapa() + ";" + C.getTitulo() + ";" + C.getDuracion() + "\n";

            fw = new FileWriter(fichero, true);
            bw = new BufferedWriter(fw);
            bw.write(Lanza);
            bw.flush();
            jtf_TituloCancion.setText("");
            jtf_TituloSingle.setText("");
            jsp_DuraCancion.setValue(1);
            jtf_FechaSingle.setText("");
            JOptionPane.showMessageDialog(JD_Artista,
                    "Single creado");

        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            bw.close();
            fw.close();
        } catch (IOException ex) {
        }

    }//GEN-LAST:event_Bt_AddSingleMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
        if (jTabbedPane1.getSelectedIndex() == 4) {
            DefaultListModel modelo = new DefaultListModel();
            for (Lanzamiento Lanzamiento1 : Lanzamientos) {
                modelo.addElement(Lanzamiento1);
            }
        }
        if (jTabbedPane1.getSelectedIndex() == 5) {
            DefaultMutableTreeNode Nodo=(DefaultMutableTreeNode)jtree_Listar.getModel().getRoot();
            for (Album albume : Autista.getAlbumes()) {
                
                DefaultMutableTreeNode M=(DefaultMutableTreeNode)Nodo.getChildAt(0);
                Nodo.add(M);
                for (Cancion cancione : albume.getCanciones()) {
                    M= new DefaultMutableTreeNode(cancione);
                }
            }
            for (Cancion cancione : Autista.getCanciones()) {
                DefaultMutableTreeNode M=(DefaultMutableTreeNode)Nodo.getChildAt(1);
                M.add(new DefaultMutableTreeNode(cancione));
            }
        }
        
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        if (jButton5.isEnabled()) {
            if (Jlst_canciones.getSelectedIndex() >= 0) {
                if(H.isAlive()){
                    H.stop();
                }
                jProgressBar1.setValue(0);
                jProgressBar1.setMaximum(60);
                Cancion c = Canciones.get(Jlst_canciones.getSelectedIndex());
                 H = new Hilo(jProgressBar1, true, c.getDuracion());
                H.start();

            }
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        repro=!repro;
        
        if(repro){
            H.resume();
        }
        else{
            H.suspend();
    }

    }//GEN-LAST:event_jButton6MouseClicked

    public void rellenarArtistas() {
        Artists.clear();
        AdminListaArtist aa = new AdminListaArtist("./Artistas.secs");
        aa.cargarArchivo();
        Artists.addAll(aa.getArtistas());
    }

    public void rellenarClientes() {
        Clients.clear();
        AdminClientes ac = new AdminClientes("./Clientes.secs");
        ac.cargarArchivo();
        Clients.addAll(ac.getClientes());

    }

    public void rellenarListas() {
        Listas.clear();
        AdminListaRep ac = new AdminListaRep("./Listas.secs");
        ac.cargarArchivo();
        Listas.addAll(ac.getListas());
    }

    public void rellenarLanzamiento() {
        try {
            for (Artista Artist : Artists) {
                Artista Ar = Artist;

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void rellenarCanciones() {
        File fichero = null;
        FileReader fr = null;
        BufferedReader br = null;

        try {
            fichero = new File("./Canciones.txt");
            fr = new FileReader(fichero);
            br = new BufferedReader(fr);
            String linea;
            while ((linea = br.readLine()) != null) {
                String lineas[] = linea.split(";");
                String nom = lineas[1];
                String duracion = lineas[2];
                Cancion C = new Cancion(nom, lineas[0], Double.parseDouble(duracion));
                Canciones.add(C);

            }
            //fin if

        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            br.close();
            fr.close();
        } catch (IOException ex) {
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    Album al;
    int cont = 0;
    public static Thread H=new Hilo() ;
    public static boolean repro=true;
    public static DefaultMutableTreeNode Nodo;
    public static Cliente Usu;
    public static Artista Autista;
    public static String Artista;
    public static ArrayList<Usuario> Users = new ArrayList<>();
    public static ArrayList<Cliente> Clients = new ArrayList<>();
    public static ArrayList<Artista> Artists = new ArrayList<>();
    public static ArrayList<Lista> Listas = new ArrayList<>();
    public static ArrayList<Lanzamiento> Lanzamientos = new ArrayList<>();
    public static ArrayList<Cancion> Canciones = new ArrayList<>();


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_AddSingle;
    private javax.swing.JDialog JD_Artista;
    private javax.swing.JDialog JD_Cliente;
    private javax.swing.JDialog JD_CrearAcount;
    private javax.swing.JDialog JD_CrearCanciones;
    private javax.swing.JList<String> Jlst_canciones;
    private javax.swing.JTextField Jtf_Contraseña;
    private javax.swing.JTextField Jtf_Usuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbt_CrearAlbum;
    private javax.swing.JButton jbt_CrearCuenta;
    private javax.swing.JComboBox<String> jcb_TipUs;
    private javax.swing.JLabel jlb_artista;
    private javax.swing.JSpinner jsp_DuraCancion;
    private javax.swing.JSpinner jsp_DuraSong;
    private javax.swing.JSpinner jsp_Edad;
    private javax.swing.JSpinner jsp_cantSongs;
    private javax.swing.JTextField jtf_Contra;
    private javax.swing.JTextField jtf_FechaPubli;
    private javax.swing.JTextField jtf_FechaSingle;
    private javax.swing.JTextField jtf_Nombre;
    private javax.swing.JTextField jtf_NombreArtist;
    private javax.swing.JTextField jtf_TituloCancion;
    private javax.swing.JTextField jtf_TituloPubli;
    private javax.swing.JTextField jtf_TituloSingle;
    private javax.swing.JTextField jtf_TituloSong;
    private javax.swing.JTree jtr_treElim;
    private javax.swing.JTree jtree_Listar;
    // End of variables declaration//GEN-END:variables
}
